// SPDX-License-Identifier: CC0-1.0
syntax = "proto3";

package mixel.asset.model.data;

import "common/program.proto";

message AnimationControllerFile {
  repeated AnimationController controllers = 1;
}

message AnimationController {
  string name = 1;
  optional string default_state = 2;
  repeated State states = 3;
}

message State {
  string name = 1;
  repeated AnimationReference animations = 2;
  repeated Transition transitions = 3;
  optional common.Program on_entry = 4;
  optional common.Program on_exit = 5;
  optional BlendTransition blend_transition = 6;
  repeated string sound_effects = 8;
}

message Transition {
  string dst = 1;
  common.Program condition = 2;
}

message AnimationReference {
  string name = 1;
  common.Program condition = 2;
}

message BlendTransition {
  optional float linear_length = 1;
  repeated BlendPoint points = 2;
}

message BlendPoint {
  float key = 1;
  float value = 2;
}
